export const IS_LOADING_ALBUMS = 'IS_LOADING_ALBUMS';
export const GET_ALBUMS = 'GET_ALBUMS';
export const FAILED_TO_GET_ALBUMS = 'FAILED_TO_GET_ALBUMS';

export const IS_LOADING_ALBUM_PHOTOS = 'IS_LOADING_ALBUM_PHOTOS';
export const GET_ALBUM_PHOTOS = 'GET_ALBUM_PHOTOS';
export const FAILED_TO_GET_ALBUM_PHOTOS = 'FAILED_TO_GET_ALBUM_PHOTOS';
